import Starry from "@/components/Starry";
import Swiper from "@/components/Swiper";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "朋友圈",
    description: "Generated by create next app",
};

export default () => {
    return (
        <>
            <div>
                <Swiper isRipple={false}>
                    {/* 星空背景组件 */}
                    <Starry />

                    {/* 分类信息 */}
                    <div className="absolute top-[35%] left-[50%] transform -translate-x-1/2 w-[80%] text-center text-white text-[20px] xs:text-[25px] sm:text-[30px] custom_text_shadow">
                        一个人的寂寞，一群人的狂欢
                    </div>
                </Swiper>
            </div>

            <div className="relative -top-36 w-[90%] xl:w-[1200px] h-[500px] mx-auto bg-white dark:bg-black-b border dark:border-black-b rounded-2xl">
                
            </div>
        </>
    )
}