import { NextUIProvider } from '@nextui-org/react';

import Header from '@/components/Header'

// 加载样式文件
import "@/styles/index.scss";
import "@/styles/tailwind.scss";

// 使用本地字体
import localFont from 'next/font/local'
const LXGWWenKai = localFont({
  src: '../assets/font/LXGWWenKai.ttf',
  display: 'swap',
})

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "宇阳 - 花有重开日，人无再少年!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${LXGWWenKai.className} dark:!bg-black-a transition-colors`}>
        <Header />

        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
