import { NextUIProvider } from '@nextui-org/react';

import Header from '@/components/Header'
import Footer from '@/components/Footer'

// 加载样式文件
import "@/styles/index.scss";
import "@/styles/tailwind.scss";

// 使用本地字体
import localFont from 'next/font/local'
const LXGWWenKai = localFont({
  src: '../assets/font/LXGWWenKai.ttf',
  display: 'swap',
})

import type { Metadata } from "next";
import Tools from '@/components/Tools';
import NProgress from '@/components/NProgress';
export const metadata: Metadata = {
  title: "宇阳 - 花有重开日，人无再少年!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${LXGWWenKai.className} dark:!bg-black-a transition-colors`}>
        {/* 进度条组件 */}
        <NProgress />
        {/* 顶部导航组件 */}
        <Header />

        {/* 主体内容 */}
        <NextUIProvider>
          {children}
        </NextUIProvider>

        {/* 底部组件 */}
        <Footer />
        {/* 右侧工具栏组件 */}
        <Tools />
      </body>
    </html>
  );
}
